################################################################################
# Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
################################################################################

components:
  - name: streammux
    parameters:
      batch-size: 4
      batched-push-timeout: 32000
      height: 1080
      live-source: true
      width: 1920
name: streammux
---
components:
  - name: object_detector
    parameters:
      batch-size: 4
  - name: resnet10_4_class_detector
    parameters:
      model-engine-file: primary.resnet10.caffemodel_b4_gpu0_int8.engine
name: object_detector
---
components:
  - name: tracker
    parameters:
      enable-batch-process: true
      ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
      ll-config-file: /opt/nvidia/deepstream/deepstream/samples/configs/deepstream-app/config_tracker_IOU.yml
      tracker-height: 384
      tracker-width: 640
name: tracker
---
components:
  - name: car_color_classifier
    parameters:
      batch-size: 16
      unique-id: 2
  - name: secondary_car_color_classifier
    parameters:
      model-engine-file: sec.carcolor.resnet18.caffemodel_b16_gpu0_int8.engine
name: car_color_classifier
---
components:
  - name: car_make_classifier
    parameters:
      batch-size: 16
      unique-id: 3
  - name: secondary_car_make_classifier
    parameters:
      model-engine-file: sec.carmake.resnet18.caffemodel_b16_gpu0_int8.engine
name: car_make_classifier
---
components:
  - name: vehicle_type_classifier
    parameters:
      batch-size: 16
      unique-id: 4
  - name: secondary_vehicle_type_classifier
    parameters:
      model-engine-file: sec.vehicletypes.resnet18.caffemodel_b16_gpu0_int8.engine
name: vehicle_type_classifier
---
components:
  - name: sample_runtime_source_manipulator
    parameters:
      interval-sec: 10
      max-num-sources: 4
      uri: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h265.mp4
name: sample_runtime_source_manipulator
