################################################################################
# Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
################################################################################

components:
  - name: multiple_source_input
    parameters:
      uri-list: file:///opt/nvidia/deepstream/deepstream/samples/streams/sonyc_mixed_audio.wav;file:///opt/nvidia/deepstream/deepstream/samples/streams/sonyc_mixed_audio.wav
name: multiple_source_input
---
components:
  - name: streammux
    parameters:
      batch-size: 2
name: streammux
---
components:
  - name: audio_classifier
    parameters:
      audio-framesize: 441000
      audio-hopsize: 110250
      audio-transform: melsdb,fft_length=2560,hop_size=692,dsp_window=hann,num_mels=128,sample_rate=44100,p2db_ref=(float)1.0,p2db_min_power=(float)0.0,p2db_top_db=(float)80.0
      batch-size: 2
  - name: sony_c_audio_classifier
    parameters:
      model-engine-file: sonyc_audio_classify.onnx_b2_gpu0_fp32.engine
name: audio_classifier
