#ifndef _DS3D_DATALOADER_LIDARSOURCE_LIDAR_FILE_SOURCE_H
#define _DS3D_DATALOADER_LIDARSOURCE_LIDAR_FILE_SOURCE_H

#include "ds3d/common/impl/impl_dataloader.h"

DS3D_EXTERN_C_BEGIN
DS3D_EXPORT_API ds3d::abiRefDataLoader *createLidarFileLoader();
DS3D_EXTERN_C_END

#endif // _DS3D_DATALOADER_DEPTHSOURCE_DEPTH_COLOR_SOURCE_H