################################################################################
# Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
################################################################################

components:
  - name: nv_ds_single_src_input39..3c18
    parameters:
      uri: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4
name: NvDsSingleSrcInput..1b00
---
components:
  - name: nv_ds_stream_mux42..36d8
    parameters:
      batch-size: 1
      height: 1080
      width: 1920
name: NvDsStreamMux..16d8
---
components:
  - name: nv_ds_msg_conv_broker61..4748
    parameters:
      msg-broker-conn-str: 127.0.0.1;9092;test-topic
      msg-broker-proto-lib: /opt/nvidia/deepstream/deepstream/lib/libnvds_kafka_proto.so
      msg-conv-config: /opt/nvidia/deepstream/deepstream/sources/apps/sample_apps/deepstream-test4/dstest4_msgconv_config.txt
      msg-conv-payload-type: 0
      topic: test-topic
name: NvDsMsgConvBroker..bb00
