################################################################################
# Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
################################################################################
components:
  - name: multiple_source_input
    parameters:
      uri-list: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_walk.mov;file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_ride_bike.mov;file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_run.mov;file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_push.mov
name: multiple_source_input
---
components:
  - name: streammux
    parameters:
      batch-size: 4
      batched-push-timeout: 40000
      height: 720
      width: 1280
name: streammux
---
components:
  - name: pre_process
    parameters:
      config-file: config_preprocess_3d_custom.txt
      # config-file: config_preprocess_2d_custom.txt
name: pre_process
---
components:
  - name: action_recognition_infer
    parameters:
      batch-size: 4
name: action_recognition_infer
