################################################################################
# Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
################################################################################
components:
  - name: nv_ds_multi_src_input0..bf50
    parameters:
      uri-list: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_walk.mov;file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_ride_bike.mov;file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_run.mov;file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_push.mov
name: NvDsMultiSrcInput..4690
---
components:
  - name: nv_ds_stream_mux3..7d10
    parameters:
      batch-size: 4
      batched-push-timeout: 40000
      height: 720
      width: 1280
name: NvDsStreamMux..bd10
---
components:
  - name: nv_ds_pre_process7..e590
    parameters:
      config-file: config_preprocess_3d_custom.txt
      # config-file: config_preprocess_2d_custom.txt
name: NvDsPreProcess..7a90
---
components:
  - name: nv_ds_infer_video11..e750
    parameters:
      batch-size: 4
name: NvDsInferVideo..b550
