################################################################################
# Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
################################################################################

components:
  - name: nv_ds_multi_src_input0..d6a0
    parameters:
      uri-list: file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4;file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h265.mp4;file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h264.mp4;file:///opt/nvidia/deepstream/deepstream/samples/streams/sample_1080p_h265.mp4
name: NvDsMultiSrcInput..2278
---
components:
  - name: nv_ds_stream_mux3..e400
    parameters:
      batch-size: 4
      batched-push-timeout: 40000
      height: 1080
      width: 1920
name: NvDsStreamMux..2198
---
components:
  - name: nv_ds_infer7..edd8
    parameters:
      batch-size: 4
  - name: resnet10_4_class_detector26..f6d8
    parameters:
      model-engine-file: primary.resnet10.caffemodel_b4_gpu0_int8.engine
name: NvDsInferVideo..2358
---
components:
  - name: per_class_object_counting22..8080
    parameters:
      overlay-count: false
name: NvDsPerClassObjectCounting..4390
