################################################################################
# Copyright (c) 2021, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
################################################################################

components:
  - name: multiple_source_input
    parameters:
      smart-rec-cache: 20
      smart-rec-container: 0
      smart-rec-dir-path: .
      smart-rec-mode: 0
      smart-record: 1
      smart-record-action: smart_record_action
      smart-record-done-signal: smart_record_done_signal
      source-id-list: 0;1;2;3
      uri-list: rtsp://127.0.0.1:8654/file-stream;rtsp://127.0.0.1:8654/file-stream;rtsp://127.0.0.1:8654/file-stream;rtsp://127.0.0.1:8654/file-stream
name: multiple_source_input
---
components:
  - name: streammux
    parameters:
      batch-size: 4
      batched-push-timeout: 40000
      height: 1080
      live-source: true
      width: 1920
name: streammux
---
components:
  - name: tracker
    parameters:
      enable-batch-process: true
      enable-past-frame: false
      ll-lib-file: /opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so
      ll-config-file: /opt/nvidia/deepstream/deepstream/samples/configs/deepstream-app/config_tracker_NvDCF_perf.yml
      tracker-height: 384
      tracker-width: 640
name: tracker
---
components:
  - name: object_detector
    parameters:
      batch-size: 4
      unique-id: 1
  - name: resnet10_4_class_detector
    parameters:
      model-engine-file: primary.resnet10.caffemodel_b4_gpu0_int8.engine
name: object_detector
---
components:
  - name: car_color_classifier
    parameters:
      batch-size: 16
      infer-on-class-ids: "0"
      infer-on-gie-id: 1
      unique-id: 5
  - name: secondary_car_color_classifier
    parameters:
      model-engine-file: sec.carcolor.resnet18.caffemodel_b16_gpu0_int8.engine
name: car_color_classifier
---
components:
  - name: car_make_classifier
    parameters:
      batch-size: 16
      infer-on-class-ids: "0"
      infer-on-gie-id: 1
      unique-id: 6
  - name: secondary_car_make_classifier
    parameters:
      model-engine-file: sec.carmake.resnet18.caffemodel_b16_gpu0_int8.engine
name: car_make_classifier
---
components:
  - name: vehicle_type_classifier
    parameters:
      batch-size: 16
      infer-on-class-ids: "0"
      infer-on-gie-id: 1
      unique-id: 4
  - name: secondary_vehicle_type_classifier
    parameters:
      model-engine-file: sec.vehicletypes.resnet18.caffemodel_b16_gpu0_int8.engine
name: vehicle_type_classifier
---
components:
  - name: tiler
    parameters:
      columns: 2
      height: 720
      rows: 2
      width: 1280
name: tiler
---
components:
  - name: onscreen_display
    parameters:
      bbox-border-colors: Car=0xff0000ff;Bicycle=0x00ffffff;Person=0x0000ffff;RoadSign=0x00ff00ff
      border-width: 1
      clock-color: 4278190335
      display-clock: false
      font: Serif
      reformat-object-labels: true
      text-bg-color: 1296911871
      text-color: 4294967295
      text-size: 15
      x-clock-offset: 800
      y-clock-offset: 820
name: onscreen_display
---
components:
  - name: kitti_dump_detector
    parameters:
      output-dir: /tmp/detector-kitti-out
name: kitti_dump_detector
---
components:
  - name: kitti_dump_tracker
    parameters:
      output-dir: /tmp/tracker-kitti-out
name: kitti_dump_tracker
---
components:
  - name: message_converter_broker
    parameters:
      msg-broker-conn-str: 127.0.0.1;9092;test-topic
      msg-broker-proto-lib: /opt/nvidia/deepstream/deepstream/lib/libnvds_kafka_proto.so
      msg-conv-config: dstest5_msgconv_sample_config.txt
      topic: test-topic
name: message_converter_broker
---
components:
  - name: sample_probe_message_meta_creation
    parameters:
      car-color-unique-id: 5
      car-make-unique-id: 6
      vehicle-type-unique-id: 4
name: sample_probe_message_meta_creation
---
components:
  - name: model_engine_watch_otf_trigger
    parameters:
      watch-file: /tmp/model-otf-test/model.engine
name: model_engine_watch_otf_trigger
---
components:
  - name: sample_cloud2device_smart_record_trigger
    parameters:
      msgconv-config: dstest5_msgconv_sample_config.txt
name: sample_cloud2device_smart_record_trigger
---
components:
  - name: message_broker_cloud2device_receiver
    parameters:
      conn-str: 127.0.0.1;9092
      proto-lib: /opt/nvidia/deepstream/deepstream/lib/libnvds_kafka_proto.so
      topics: test-topic-sr
name: message_broker_cloud2device_receiver
