################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
################################################################################
# this  Makefile is to be used to build the test application to exercise the sample mqtt protocol adaptor
CXX:=g++
NVDS_VERSION:=6.3
DS_INC:= /opt/nvidia/deepstream/deepstream-$(NVDS_VERSION)/sources/includes/

DS_LIB:=/opt/nvidia/deepstream/deepstream-$(NVDS_VERSION)/lib/

ASYNC_SEND_BIN:= test_mqtt_proto_async

ASYNC_SEND_SRCS:=test_mqtt_proto_async.cpp

CXXFLAGS:= -I$(DS_INC) -rdynamic
LDFLAGS:= -L$(DS_LIB) -ldl -pthread -Wl,-rpath=$(DS_LIB)

default: all

all: $(ASYNC_SEND_BIN)

$(ASYNC_SEND_BIN) : $(ASYNC_SEND_SRCS)
	$(CXX) -o $@ $^  $(CXXFLAGS) $(LDFLAGS)

clean:
	rm -rf $(ASYNC_SEND_BIN)
