################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
################################################################################

name: "bevfusion"
backend: "python"

input [
  {
    name: "input_image_0"
    data_type: TYPE_UINT8
    dims: [1,900,1600,4]
  }
]
input [
  {
    name: "input_image_1"
    data_type: TYPE_UINT8
    dims: [1,900,1600,4]
  }
]
input [
  {
    name: "input_image_2"
    data_type: TYPE_UINT8
    dims: [1,900,1600,4]
  }
]
input [
  {
    name: "input_image_3"
    data_type: TYPE_UINT8
    dims: [1,900,1600,4]
  }
]
input [
  {
    name: "input_image_4"
    data_type: TYPE_UINT8
    dims: [1,900,1600,4]
  }
]
input [
  {
    name: "input_image_5"
    data_type: TYPE_UINT8
    dims: [1,900,1600,4]
  }
]
input [
  {
    name: "input_lidar"
    data_type: TYPE_FP32
    dims: [242180,4]
  }
]
output [
  {
    name: "output_3d_bbox"
    data_type: TYPE_FP32
    dims: [1,-1,-1]
  }
]

instance_group [{
    count: 1
    kind: KIND_GPU
    }
]

parameters: { key: "FORCE_CPU_ONLY_INPUT_TENSORS" value: {string_value:"no"}}
