/**
 * @file
 * <b>Metadata manipulation interfaces </b>
 *
 * Metadata is carried by a buffer and is accessible via buffer probe or
 * data receiver
 *
 */
#ifndef NVIDIA_DEEPSTREAM_METADATA
#define NVIDIA_DEEPSTREAM_METADATA

#include <functional>
#include <memory>
#include <string>

#include "nvds_tracker_meta.h"
#include "nvll_osd_struct.h"

namespace deepstream {

#define USER_METADATA_START = (4096 + 4096 + 1)

/**
 * @brief Metadata base class
 *
 * The clas is not supposed to be used directly except that users want
 * to create their own derived metadata class
 *
 **/
class Metadata {
public:
    /** @brief Constructor through an opqaue pinter */
    Metadata(void *data);

    /** @brief Destructor */
    virtual ~Metadata();

    /** @brief operator to check if a metadata is void */
    virtual operator bool() { return data_ != nullptr; }

protected:
    void *data_; //> opaque data pointer
};

/**
 * @brief metadata iterator template
 *
 * Template parameter T is one of the derived class of Metadata.
 * The template is used with those metadata which contains a list of sub-metadata
 *
 * */
template <typename T>
class AbstractIterator {
public:
    /** @brief Construct an iterator for an iterable metadata */
    AbstractIterator(const T &data) : data_(data) {}

    /** @brief Destructor */
    virtual ~AbstractIterator() {}

    /** @brief Dereference the associated metadata */
    T &operator*() { return data_; }

    /** @brief Dereference the associated metadata as a pointer*/
    T *operator->() { return &data_; }

    /** @brief Directly access the associated metadata */
    T &get() { return data_; }

    /** @brief advances the iterator to access the next data */
    virtual AbstractIterator<T> &next() = 0;

    /** @brief check if the end is reached */
    virtual bool done() = 0;

    /** @brief check if two iterator point to the same position */
    virtual bool operator==(const AbstractIterator<T> &other) const = 0;

    /** @brief check if two iterator point to different position */
    bool operator!=(const AbstractIterator<T> &other) const { return !(*this == other); }

protected:
    T data_;
};

/** @brief Base class of user defined metadata */
class UserMetadata : public Metadata {
public:
    typedef std::unique_ptr<AbstractIterator<UserMetadata>> Iterator;

    /**
     * @brief Constructor through opaque data pointer
     *
     * By default an empty user metadata object is created.
     *
     */
    UserMetadata(void *);
    /** @brief Destructor */
    virtual ~UserMetadata();

    /** @brief operator to check if a metadata is void */
    virtual operator bool() override { return data_ != nullptr; }

    friend class BatchMetadata;
    friend class FrameMetadata;

protected:
    void get_(void *&);
};

/** @brief Meta generated from a classifier */
class ClassifierMetadata : public Metadata {
public:
    typedef std::unique_ptr<AbstractIterator<ClassifierMetadata>> Iterator;

    /**
     * @brief Constructor through opaque data pointer
     *
     * By default an empty classifier metadata object is created.
     *
     */
    ClassifierMetadata(void *data = nullptr);
    /** @brief Destructor */
    virtual ~ClassifierMetadata();

    /** @brief Number of the lables generated by the classifier */
    unsigned int nLabels() const;
    /** @brief Identifying the unique component that generates the metadata */
    unsigned int uniqueComponentId() const;
    /** @brief Get the nth label */
    std::string getLabel(unsigned int nth) const;
};

/**
 * @brief Object metadata
 *
 * The metadata is for describing a detected object
 *
 **/
class ObjectMetadata : public Metadata {
public:
    typedef std::unique_ptr<AbstractIterator<ObjectMetadata>> Iterator;

    /**
     * @brief Constructor through opaque data pointer
     *
     * By default an empty object metadata object is created.
     *
     */
    ObjectMetadata(void *data = nullptr);
    /** @brief Destructor */
    virtual ~ObjectMetadata();

    /** @brief Number to identify the unique component that generates the metadata */
    unsigned int uniqueComponentId() const;
    void setUniqueComponentId(unsigned int);
    /** @brief Number to identify the class of the object */
    unsigned int classId() const;
    void setClassId(unsigned int);
    /** @brief Number to identify the object which is tracked in the scene */
    unsigned long int objectId() const;
    void setObjectId(unsigned long);
    /** @brief Confidence level */
    float confidence() const;
    void setConfidence(float);
    /** @brief Confidence level from tracker */
    float trackerConfidence() const;
    void setTrackerConfidence(float);
    /** @brief Bounding box of the object */
    NvOSD_RectParams &rectParams() const;
    void setRectParams(const NvOSD_RectParams &);
    /** @brief Holds mask parameters for the object. This mask is overlayed on object */
    NvOSD_MaskParams &maskParams() const;
    void setMaskParams(const NvOSD_MaskParams &);
    /** @brief Formated text description of the object, controlling osd display */
    NvOSD_TextParams &textParams() const;
    void setTextParams(const NvOSD_TextParams &);
    /** @brief A string to describe the object class */
    std::string label() const;
    void setLabel(std::string);
    /** @brief Bounding box of the object */
    NvBbox_Coords &nvBboxInfo() const;
    void setNvBboxInfo(const NvBbox_Coords &);

    /** @brief Iterate the classifier metadata within it */
    unsigned int iterate(const std::function<void(const ClassifierMetadata &)> &func) const;
    /** @brief Get the iterator for object metadata within it */
    void initiateIterator(ClassifierMetadata::Iterator &) const;

    /** @brief Iterate the user metadata within it */
    unsigned int iterate(const std::function<void(const UserMetadata &)> &func,
                         int meta_type) const;
    /** @brief Get the iterator for user metadata within it */
    void initiateIterator(UserMetadata::Iterator &, int meta_type) const;

    friend class FrameMetadata;
};

class FrameMetadata;
/**
 * @brief User metadata for event message
 *
 * Objects can be attached to the event message meta for triggering an event
 * in "nvmsgconv" element.
 *
 **/
class EventMessageUserMetadata : public UserMetadata {
public:
    EventMessageUserMetadata(void *data = nullptr);
    virtual ~EventMessageUserMetadata();

    /** @brief generate an event by attaching an object */
    void generate(const ObjectMetadata &,
                  const FrameMetadata &,
                  const std::string sensor = "N/A",
                  const std::string uri = "N/A",
                  const std::vector<std::string> labels = std::vector<std::string>());
};

/**
 * @brief ROI metadata
 *
 * The metadata is for describing a region of interest
 *
 **/
class RoiMetadata : public Metadata {
public:
    RoiMetadata(void *data = nullptr);
    virtual ~RoiMetadata();

    /** @brief Get the region of interest */
    NvOSD_RectParams &rectParams() const;

    /** @brief Get the frame metadata */
    FrameMetadata frameMetadata() const;

    /** @brief Get the object metadata */
    ObjectMetadata objectMetadata() const;

    /** @brief Iterate the user metadata within it */
    unsigned int iterate(const std::function<void(const UserMetadata &)> &func,
                         int meta_type) const;
    /** @brief Get the iterator for user metadata within it */
    void initiateIterator(UserMetadata::Iterator &, int meta_type) const;

    /** @brief Get the classifier metadata within it */
    unsigned int iterate(const std::function<void(const ClassifierMetadata &)> &func) const;
    /** @brief Get the iterator for classifier metadata within it */
    void initiateIterator(ClassifierMetadata::Iterator &) const;
};

/**
 * @brief User metadata for tensor output
 *
 * this user metadata object is associated with a tensor structure
 */
class Tensor;
class TensorOutputUserMetadata : public UserMetadata {
public:
    TensorOutputUserMetadata(void *data = nullptr);
    TensorOutputUserMetadata(const UserMetadata &);
    virtual ~TensorOutputUserMetadata();

    /** @brief id for inference instance */
    unsigned int uniqueId() const;
    /** @brief get tensor output layers */
    std::unordered_map<std::string, Tensor *> getLayers();
};

/**
 * @class SegmentationUserMetadata
 * @brief A class to handle user metadata for segmentation.
 *
 * This class extends the UserMetadata class and provides additional
 * functionality specific to segmentation metadata.
 */

class SegmentationUserMetadata : public UserMetadata {
public:
    /**
     * @brief Constructor for SegmentationUserMetadata.
     *
     * @param data Optional pointer to data. Defaults to nullptr.
     */
    SegmentationUserMetadata(void *data = nullptr);

    /** @brief Copy constructor for SegmentationUserMetadata. */
    SegmentationUserMetadata(const UserMetadata &other);

    /** @brief Destructor for SegmentationUserMetadata. */
    virtual ~SegmentationUserMetadata();

    /** @brief Get the unique identifier for this metadata. */
    unsigned int uniqueId() const;

    /** @brief Get the number of classes in the segmentation. */
    unsigned int getClasses() const;

    /** @brief Get the width of the segmentation map. */
    unsigned int getWidth() const;

    /** @brief Get the height of the segmentation map. */
    unsigned int getHeight() const;

    /** @brief Get the class map for the segmentation. */
    const int *getClassMap() const;

    /** @brief Get the class probabilities map for the segmentation. */
    const float *getClassProbabilitiesMap() const;
};

/**
 * @brief Template for customized user metadata
 *
 * Custom objects can be attached to user metadata via this template
 *
 **/
template <class C, int N>
class UserMetadataTemplate : public UserMetadata {
public:
    UserMetadataTemplate(void *data = nullptr) : UserMetadata(data) {}
    UserMetadataTemplate(const UserMetadata &other) : UserMetadata(other) {}
    virtual ~UserMetadataTemplate() {}

    C &get()
    {
        void *p = nullptr;
        this->get_(p);
        return *((C *)p);
    }

    static void *copy(void *data, void *user_data)
    {
        void *p = nullptr;
        UserMetadataTemplate<C, N>(data).get_(p);
        C *&src = (C *&)p;
        C *dst = new C(*src);
        return dst;
    }

    static void free(void *data, void *user_data)
    {
        void *p = nullptr;
        UserMetadataTemplate<C, N>(data).get_(p);
        C *&src = (C *&)p;
        delete src;
        p = nullptr;
    }
};

/**
 * @brief Metadata for overlay display on a frame
 *
 * The metadata is for nvosd element display various shapes on the curernt
 * frame.
 *
 **/
class DisplayMetadata : public Metadata {
public:
    typedef std::unique_ptr<AbstractIterator<DisplayMetadata>> Iterator;

    /**
     * @brief Constructor through opaque data pointer
     *
     * By default an empty display metadata object is created.
     *
     */
    DisplayMetadata(void *data = nullptr);
    /** @brief Destructor */
    virtual ~DisplayMetadata();

    /** @brief Number of the rectangles */
    unsigned int nRects() const;
    /** @brief Number of the labels */
    unsigned int nLabels() const;
    /** @brief Number of the lines */
    unsigned int nLines() const;
    /** @brief Number of the arrows */
    unsigned int nArrows() const;
    /** @brief Number of the circles */
    unsigned int nCircles() const;

    /** @brief Add a text label */
    bool add(NvOSD_TextParams &);
    /** @brief Add a rectangle */
    bool add(NvOSD_RectParams &);
    /** @brief Add a line */
    bool add(NvOSD_LineParams &);
    /** @brief Add an arrow */
    bool add(NvOSD_ArrowParams &);
    /** @brief Add a circle */
    bool add(NvOSD_CircleParams &);

    friend class FrameMetadata;
};

/**
 * @brief Holds information for a single frame.
 *
 * Iterable via iterators for ObjectMetadata and DisplayMetadata.
 *
 */
class FrameMetadata : public Metadata {
public:
    typedef std::unique_ptr<AbstractIterator<FrameMetadata>> Iterator;

    /**
     * @brief Constructor through opaque data pointer
     *
     * By default an empty frame metadata object is created.
     *
     */
    FrameMetadata(void *data = nullptr);
    /** @brief Destructor */
    virtual ~FrameMetadata();

    /** @brief Iterate the object metadata within it */
    unsigned int iterate(const std::function<void(const ObjectMetadata &)> &func) const;
    /** @brief Get the iterator for object metadata within it */
    void initiateIterator(ObjectMetadata::Iterator &) const;

    /** @brief Iterate the display metadata within it */
    unsigned int iterate(const std::function<void(const DisplayMetadata &)> &func) const;
    /** @brief Get the iterator for display metadata within it */
    void initiateIterator(DisplayMetadata::Iterator &) const;

    /** @brief Iterate the user metadata within it */
    unsigned int iterate(const std::function<void(const UserMetadata &)> &func,
                         int meta_type) const;
    /** @brief Get the iterator for user metadata within it */
    void initiateIterator(UserMetadata::Iterator &, int meta_type) const;

    /** @brief Index of the pad from which the frame is generated */
    unsigned int padIndex() const;
    /** @brief Location the frame in the batch */
    unsigned int batchId() const;
    /** @brief Frame number */
    int frameNum() const;
    /** @brief Identify the source of the frame, e.g. camera ID */
    unsigned int sourceId() const;
    /** @brief Picture width of the source */
    unsigned int sourceWidth() const;
    /** @brief Picture height of the source */
    unsigned int sourceHeight() const;

    /** @brief Picture width of the pipeline */
    unsigned int pipelineWidth() const;
    /** @brief Picture height of the pipeline */
    unsigned int pipelineHeight() const;

    /** Holds the presentation timestamp (PTS) of the frame. */
    uint64_t bufferPTS() const;
    /** Holds the ntp timestamp. */
    uint64_t ntpTimestamp() const;

    /** @brief Append display metadata to the frame */
    void append(const DisplayMetadata &);
    /** @brief Append user metadata to the frame */
    void append(const UserMetadata &);
    /** @brief Append object metadata to the frame */
    void append(const ObjectMetadata &);

    friend class BatchMetadata;
};

/**
 * @brief Metadata for preprocessed tensor
 *
 * This user metadata object is associated with a preprocessed tensor structure
 */
class PreprocessTensorMetadata {
public:
    PreprocessTensorMetadata(void *data = nullptr);
    virtual ~PreprocessTensorMetadata();

    /** @brief Get the name of the tensor */
    std::string getName() const;

    /** @brief Get the meta id of the tensor */
    unsigned int getMetaId() const;

    /** @brief Get the tensor */
    Tensor *getTensor() const;

    operator bool() const { return data_ != nullptr; }

protected:
    void *data_;
};

/**
 * @brief User metadata for preprocess batch
 *
 * This user metadata object is associated with a preprocess batch structure
 */
class PreprocessBatchUserMetadata : public UserMetadata {
public:
    PreprocessBatchUserMetadata(void *data = nullptr);
    PreprocessBatchUserMetadata(const UserMetadata &);
    virtual ~PreprocessBatchUserMetadata();

    /** @Brief Get the target unique ids */
    std::vector<unsigned int> getTargetUniqueIds() const;

    /** @brief Get the roi list */
    std::vector<RoiMetadata> getRois() const;

    /** @brief Get the preprocess tensor metadata */
    PreprocessTensorMetadata getPreprocessTensorMetadata() const;

    /** @brief Initialize a preprocess tensor metadata */
    bool initPreprocessTensorMetadata(const std::string &name,
                                      unsigned int meta_id,
                                      unsigned int unique_id,
                                      Tensor *tensor);
};

class ObjectVisibilityUserMetadata : public UserMetadata {
public:
    ObjectVisibilityUserMetadata(void *data = nullptr);
    ObjectVisibilityUserMetadata(const UserMetadata &user_meta);
    virtual ~ObjectVisibilityUserMetadata();

    /** @brief Get the visibility of the object */
    float getVisibility() const;
};

class ObjectImageFootLocationUserMetadata : public UserMetadata {
public:
    ObjectImageFootLocationUserMetadata(void *data = nullptr);
    ObjectImageFootLocationUserMetadata(const UserMetadata &user_meta);
    virtual ~ObjectImageFootLocationUserMetadata();

    /** @brief Get the image foot location of the object */
    std::pair<float, float> getImageFootLocation() const;
};

class Object3DBBoxUserMetadata : public UserMetadata {
public:
    Object3DBBoxUserMetadata(void *data = nullptr);
    Object3DBBoxUserMetadata(const UserMetadata &user_meta);
    virtual ~Object3DBBoxUserMetadata();
    NvDsObj3DBbox *get3DBbox() const;
};

class TrackerPastFrameUserMetadata : public UserMetadata {
public:
    TrackerPastFrameUserMetadata(void *data = nullptr);
    TrackerPastFrameUserMetadata(const UserMetadata &user_meta);
    virtual ~TrackerPastFrameUserMetadata();
    NvDsTargetMiscDataBatch *getTrackerMiscDataBatch() const;
};

class AnalyticsObjInfo : public UserMetadata {
public:
    /**
     * @brief Constructor for AnalyticsObjInfo.
     *
     * @param data Optional pointer to data. Defaults to nullptr.
     */
    AnalyticsObjInfo(void *data = nullptr);

    /** @brief Copy constructor for AnalyticsObjInfo. */
    AnalyticsObjInfo(const UserMetadata &user_meta);

    /** @brief Destructor for AnalyticsObjInfo. */
    virtual ~AnalyticsObjInfo();

    /** @brief Get the ROI status. */
    std::vector<std::string> getRoiStatus() const;

    /** @brief Get the overcrowding status. */
    std::vector<std::string> getOcStatus() const;

    /** @brief Get the line crossing status. */
    std::vector<std::string> getLcStatus() const;

    /** @brief Get the direction status. */
    std::string getDirStatus() const;

    /** @brief Get the unique identifier for this metadata. */
    unsigned int getUniqueId() const;

    /** @brief Get the object status. */
    std::string getObjStatus() const;
};

class AnalyticsFrameMeta : public UserMetadata {
public:
    /**
     * @brief Constructor for AnalyticsFrameMeta.
     *
     * @param data Optional pointer to data. Defaults to nullptr.
     */
    AnalyticsFrameMeta(void *data = nullptr);

    /** @brief Copy constructor for AnalyticsFrameMeta. */
    AnalyticsFrameMeta(const UserMetadata &user_meta);
    virtual ~AnalyticsFrameMeta();

    /** @brief  Map of boolean status of overcrowding for configured ROIs,
     * which can be accessed using key, value pair; where key is the ROI label
     */
    std::unordered_map<std::string, bool> getOcStatus() const;

    /** @brief Map of total count of valid objects in ROI  for configured ROIs,
     * which can be accessed using key, value pair; where key is the ROI label
     */
    std::unordered_map<std::string, uint32_t> getObjInROIcnt() const;

    /** @brief Map of total count of Line crossing in current frame for configured lines,
     * which can be accessed using key, value pair; where key is the ROI label
     */
    std::unordered_map<std::string, uint64_t> getObjLCCurrCnt() const;

    /** @brief Map of total cumulative count of Line crossing for configured lines,
     * which can be accessed using key, value pair; where key is the ROI label
     */
    std::unordered_map<std::string, uint64_t> getObjLCCumCnt() const;

    /** @brief Get the unique identifier for this metadata. */
    unsigned int getUniqueId() const;

    /** @brief Map of total count of objects for each class ID,
     * which can be accessed using key, value pair; where key is class ID
     */
    std::unordered_map<int, uint32_t> getObjCnt() const;
};

/**
 * @brief Holds information about a formed batch containingframes from different sources.
 *
 * Iterable via iterators for FrameMetadata and UserMetadata.
 * Support initiaizing sub-metadata including DisplayMetadata, FrameMetadata, ObjectMetadata,
 * EventMessageUserMetadata via acquire method. The aquired metadata objects are set to the
 * default state and the their lifecycle would be managed by the batch metadata automatically.
 *
 */
class BatchMetadata : public Metadata {
public:
    /**
     * @brief Constructor through opaque data pointer
     *
     * By default an empty batch metadata object is created.
     *
     */
    BatchMetadata(void *data = nullptr);

    /** @brief Destructor */
    virtual ~BatchMetadata();

    /** @brief Iterate the frame metadata within it */
    unsigned int iterate(const std::function<void(const FrameMetadata &)> &func) const;
    /** @brief Get the iterator for frame metadata within it */
    void initiateIterator(FrameMetadata::Iterator &) const;

    /** @brief Iterate the user metadata within it */
    unsigned int iterate(const std::function<void(const UserMetadata &)> &func,
                         int meta_type) const;
    /** @brief Get the iterator for user metadata within it */
    void initiateIterator(UserMetadata::Iterator &, int meta_type) const;

    /** @brief Initialize an empty display metadata */
    bool acquire(DisplayMetadata &);
    /** @brief Initialize an empty frame metadata */
    bool acquire(FrameMetadata &);
    /** @brief Initialize an empty object metadata */
    bool acquire(ObjectMetadata &);
    /** @brief Initialize an empty event message user metadata */
    bool acquire(EventMessageUserMetadata &);
    /** @brief Initialize an empty preprocess batch user metadata */
    bool acquire(PreprocessBatchUserMetadata &);
    /** @brief Initialize an empty user metadata through template */
    template <class C, int N>
    bool acquire(UserMetadataTemplate<C, N> &user_meta)
    {
        user_meta = acquireUserMetadata_(new C, N, UserMetadataTemplate<C, N>::copy,
                                         UserMetadataTemplate<C, N>::free);
        return user_meta ? true : false;
    }

    /** @brief Append a frame metadata to the batch */
    void append(const FrameMetadata &);
    /** @brief Append a user metadata to the batch */
    void append(const UserMetadata &);

    /** @brief Number of frames in the batch*/
    unsigned int nFrames() const;

protected:
    UserMetadata acquireUserMetadata_(void *data,
                                      unsigned int type,
                                      void *(*copy)(void *, void *),
                                      void (*free)(void *, void *));
};

} // namespace deepstream

#endif