#ifndef __GST_DSEXAMPLE_CUDA_H__
#define __GST_DSEXAMPLE_CUDA_H__

#include <gst/base/gstbasetransform.h>
#include <gst/video/video.h>

/* Open CV headers */
#pragma GCC diagnostic push
#if __GNUC__ >= 8
#pragma GCC diagnostic ignored "-Wclass-memaccess"
#endif
#ifdef WITH_OPENCV
#include "opencv2/core/cuda.hpp"
#include "opencv2/cudafilters.hpp"
#include "opencv2/cudaimgproc.hpp"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/imgproc/imgproc.hpp"
#endif
#pragma GCC diagnostic pop

#include <cuda.h>
#include <cuda_runtime.h>

#include "dsexample_lib/dsexample_lib.h"
#include "gst-nvquery.h"
#include "gstnvdsmeta.h"
#include "nvbufsurface.h"
#include "nvbufsurftransform.h"

/* Package and library details required for plugin_init */
#define PACKAGE "dsexample"
#define VERSION "1.0"
#define LICENSE "Proprietary"
#define DESCRIPTION "NVIDIA example plugin for integration with DeepStream on DGPU"
#define BINARY_PACKAGE "NVIDIA DeepStream 3rdparty IP integration example plugin"
#define URL "http://nvidia.com/"

G_BEGIN_DECLS
/* Standard boilerplate stuff */
typedef struct _GstDsExample GstDsExample;
typedef struct _GstDsExampleClass GstDsExampleClass;

/* Standard boilerplate stuff */
#define GST_TYPE_DSEXAMPLE (gst_dsexample_get_type())
#define GST_DSEXAMPLE(obj) (G_TYPE_CHECK_INSTANCE_CAST((obj), GST_TYPE_DSEXAMPLE, GstDsExample))
#define GST_DSEXAMPLE_CLASS(klass) \
    (G_TYPE_CHECK_CLASS_CAST((klass), GST_TYPE_DSEXAMPLE, GstDsExampleClass))
#define GST_DSEXAMPLE_GET_CLASS(obj) \
    (G_TYPE_INSTANCE_GET_CLASS((obj), GST_TYPE_DSEXAMPLE, GstDsExampleClass))
#define GST_IS_DSEXAMPLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE((obj), GST_TYPE_DSEXAMPLE))
#define GST_IS_DSEXAMPLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE((klass), GST_TYPE_DSEXAMPLE))
#define GST_DSEXAMPLE_CAST(obj) ((GstDsExample *)(obj))

/** Maximum batch size to be supported by dsexample. */
#define NVDSEXAMPLE_MAX_BATCH_SIZE 1024

struct _GstDsExample {
    GstBaseTransform base_trans;

    // Context of the custom algorithm library
    DsExampleCtx *dsexamplelib_ctx;

    // Unique ID of the element. The labels generated by the element will be
    // updated at index `unique_id` of attr_info array in NvDsObjectParams.
    guint unique_id;

    // Frame number of the current input buffer
    guint64 frame_num;

    // CUDA Stream used for allocating the CUDA task
    cudaStream_t cuda_stream;

    // Device buffer to store RGB data for use by algorithm
    void *device_rgb_buf;

    // the intermediate scratch buffer for conversions RGBA
    NvBufSurface *inter_buf;

#ifdef WITH_OPENCV
    // OpenCV GPU mat containing RGB data
    cv::cuda::GpuMat *cvgpumat;
#endif

    // Input video info (resolution, color format, framerate, etc)
    GstVideoInfo video_info;

    // Resolution at which frames/objects should be processed
    gint processing_width;
    gint processing_height;

    // Flag which defince igpu/dgpu
    guint is_integrated;

    // Maximum batch size
    guint max_batch_size;

    // GPU ID on which we expect to execute the task
    guint gpu_id;

    // Boolean indicating if entire frame or cropped objects should be processed
    gboolean process_full_frame;

    // Boolean indicating if to blur the detected objects
    gboolean blur_objects;

    /** Config params required by NvBufSurfTransform API. */
    NvBufSurfTransformConfigParams transform_config_params;
};

// Boiler plate stuff
struct _GstDsExampleClass {
    GstBaseTransformClass parent_class;
};

GType gst_dsexample_get_type(void);

G_END_DECLS
#endif /* __GST_DSEXAMPLE_H__ */
